config/routes.rb
Lotto::Application.routes.draw do
  root :to => "pages#index"
  match 'pages/:action', :controller => 'pages'
  devise_for :users
  resources :bets
  match '/bets/:id/show_last_five' => 'bets#show_last_five', :as => 'show_last_five'
  match 'cancel' => 'bets#cancel', :as => 'cancel'
  match '/bets' => 'bets#index', :as => 'user_root'

end

app/models/bet.rb
# encoding: utf-8

require './lib/numbers_handler'

class Bet < ActiveRecord::Base
  include NumbersHandler
  
  belongs_to :user
  belongs_to :lotto_type
  
  validates :numbers, :user_id, :lotto_type_id, :presence => true
  validates :numbers, :format => { :with => /\A[0-9,]+\z/, :message => "apenas números e vírgulas são permitidos" }
  
  before_save :normalize_numbers # NumbersHandler method
  after_find :split_numbers # NumbersHandler method
  after_save :split_numbers
  
  def last_result
    type = self.lotto_type

    if type.name == 'Dupla-Sena'
      results = type.results.limit(2).order('contest DESC')
      hits = [count_hits(numbers, results[0].numbers), count_hits(numbers, results[1].numbers)]
    else
      result = type.results.limit(1).order('contest DESC')[0]
      hits = count_hits(numbers, result.numbers)
    end

    hits
  end

  def last_five_results
    type = self.lotto_type
    results = [[], []]

    if type.name == 'Dupla-Sena'
      contests = type.results.limit(12).order('contest DESC')
      2.times { contests.delete_at(0) }
      contests.size.times do |i|
        unless i.even?
          results[0] << contests[i].contest
          results[1] << [count_hits(numbers, contests[i-1].numbers), count_hits(numbers, contests[i].numbers)]
        end
      end
    else
      contests = type.results.limit(6).order('contest DESC')
      contests.delete_at(0)
      contests.each do |con|
        results[0] << con.contest
        results[1] << count_hits(numbers, con.numbers)
      end
    end

    results
  end

  def type_matches?(id)
    return true if id == self.lotto_type_id
  end
  
  def show_numbers
    self.numbers.join(' - ')
  end

  private
  def count_hits(betnum, resnum)
    hits = 0
    betnum.each do |num|
      hits += 1 if resnum.include?(num)
    end

    hits
  end
end

app/models/lotto_type.rb
class LottoType < ActiveRecord::Base
  has_many :bets, :dependent => :nullify
  has_many :results, :dependent => :nullify
end

app/models/result.rb
# encoding: utf-8

require './lib/numbers_handler'
require 'mechanize'

class Result < ActiveRecord::Base
  include NumbersHandler
  
  $agent = Mechanize.new
  
  belongs_to :lotto_type
  
  validates :numbers, :contest, :lotto_type_id, :presence => true
  
  before_save :normalize_result_numbers
  after_find :split_numbers # NumbersHandler method
  after_save :split_numbers
  
  def self.updates_lotofacil
    brazilian_time = Time.now - 10800
    if brazilian_time.monday? or brazilian_time.wednesday? or brazilian_time.friday?
      numbers = []
      page = $agent.get('http://www1.caixa.gov.br/loterias/loterias/lotofacil/lotofacil_pesquisa_new.asp')
      values = page.body.split('|')[3..17]
      numbers << values.map {|num| num.to_i}
      contest = page.body.split('|')[0].to_i

      update!('Lotofácil', contest, numbers)
    else
      puts "Not today."
    end
  end

  def self.updates_duplasena
    brazilian_time = Time.now - 10800
    if brazilian_time.tuesday? or brazilian_time.friday?
      numbers = [[], []]
      page = $agent.get('http://www1.caixa.gov.br/loterias/loterias/duplasena/duplasena_pesquisa_new.asp')
      contest = page.body.split('|')[0].to_i
      search = page.search('li')
      0.upto(11) do |i|
        if i < 6
          numbers[0] << search[i].text.to_i
        else
          numbers[1] << search[i].text.to_i
        end
      end

      update!('Dupla-Sena', contest, numbers)
    else
      puts "Not today."
    end
  end

  def self.updates_lotomania
    brazilian_time = Time.now - 10800
    if brazilian_time.wednesday? or brazilian_time.saturday?
      numbers = []
      page = $agent.get('http://www1.caixa.gov.br/loterias/loterias/lotomania/_lotomania_pesquisa.asp')
      contest = page.body.split('|')[0].to_i
      values = page.body.split('|')[6..25]
      numbers << values.map { |num| num.to_i }
      
      update!('Lotomania', contest, numbers)
    else
      puts 'Not Today.'
    end
  end

  def self.update!(typename, contest, numbers)
    type = LottoType.find_by_name("#{typename}")
    last_result = type.results.limit(1).order('contest DESC')[0]

    numbers.each do |numbers|
      if last_result.contest < contest
        result = type.results.new
        result.numbers = numbers
        result.contest = contest
        result.save if result.valid?
        puts "Updated!"
      else
        puts "Already updated."
        break
      end
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bets
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @bets = current_user.bets.all
    
    respond_to do |format|
      format.html
    end
  end
  
  def show
    
  end
  
  def new
    @bet = current_user.bets.new
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def create
    @bet = current_user.bets.new(params[:bet])
    
    if @bet.save
      respond_to do |format|
        format.html { redirect_to @bet, :notice => 'Aposta criada' }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new, :alert => 'Nao foi possivel criar a aposta' }
        format.js { render 'fail_create.js.erb' }
      end
    end
  end

  def show_last_five
    @bet = current_user.bets.find(params[:id])
    @result = @bet.last_five_results
    respond_to do |format|
      format.js
    end
  end
  
  def edit
    @bet = current_user.bets.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def update
    @bet = current_user.bets.find(params[:id])
    if @bet.update_attributes(params[:bet])
      respond_to do |format|
        format.html { redirect_to @bet, :alert => 'Aposta atualizada' }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :edit, :alert => 'Nao foi possivel editar a aposta' }
        format.js { render 'fail_create.js.erb' }        
      end
    end
  end
  
  def destroy
    @bet = current_user.bets.find(params[:id])
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to root_path, :alert => 'Aposta apagada' }
      format.js
    end
  end
  
  def cancel
    render 'cancel.js.erb'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'index'
  
  def index
    if user_signed_in?
      redirect_to user_root_path
    else
      render :action => 'index'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu
    if user_signed_in?
      render 'devise/menu/user_menu'
    else
      render 'devise/menu/regular_menu'
    end
  end
end

app/helpers/bets_helper.rb
module BetsHelper
  def submit_or_cancel(form, name='Cancel')
    if @bet.numbers.nil?
      return form.submit('Criar', :class => 'btn btn-primary') + ' ' + link_to('Cancelar', cancel_path(:format => :js), :remote => true, :class => 'cancel btn')
    else
      return form.submit('Atualizar', :class => 'btn btn-primary') + ' ' + link_to('Cancelar', cancel_path(:format => :js), :remote => true, :class => 'cancel btn')
    end
  end

  def show_result(bet)
  	if bet.lotto_type.name == 'Dupla-Sena'
  		return bet.last_result[0].to_s + ' e ' + bet.last_result[1].to_s
  	else
  		return bet.last_result.to_s
  	end
  end

  def show_last_five_results(result, i)
    if result[1][0].is_a? Array
      return result[1][i][0].to_s + ' e ' + result[1][i][1].to_s
    else
      return result[1][i]
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bets/_bet.html.erb
<tr id="<%= dom_id(bet) %>">
  <td class="td-nowrap"><%= bet.lotto_type.name %></td>
  <td><%= bet.show_numbers %></td>
  <td><%= show_result(bet) %></td>
  <td><%= bet.lotto_type.results.limit(1).order('contest DESC')[0].contest.to_s %></td>
  <td class="td-nowrap"><%= link_to 'Editar', edit_bet_path(bet, :format => :js), :remote => true, :class => 'edit_bet_link btn btn-mini', :id => dom_id(bet) + '_edit_link' %> <%= link_to "Últimos 5", show_last_five_path(bet, :format => :js), :remote => true, :class => 'show_last_five_link btn btn-mini', :id => dom_id(bet) + '_last_five_link' %> <%= link_to "Deletar", bet, :confirm => 'Você tem certeza?', :method => :delete, :remote => true, :class => 'destroy_bet_link btn btn-danger btn-mini', :id => dom_id(bet) + '_delete_link' %></td>
</tr>

app/views/bets/_form.html.erb
<%= form_for @bet, :remote => true, :html => {:class => 'form-horizontal new_bet'} do |b| %>
  <fieldset>
    <div class="control-group">
      <%= b.label :lotto_type_id, 'Tipo', :class => 'control-label' %>
      <div class="controls">
      <% LottoType.all.each do |type| %>
        <label class="radio inline">
          <%= radio_button_tag 'bet[lotto_type_id]', type.id, @bet.type_matches?(type.id), :class => 'radio inline', :id => dom_id(type) %> <%= type.name %>
        </label>
      <% end %>
      </div>
    </div>

    <div class="control-group">
      <%= b.label :numbers, 'Números', :class => 'control-label' %>
      <div class="controls">
        <%= b.text_field :numbers %>
        <p class="help-block">Digite somente números separados por vírgulas. (Ex: 3,13,27...)</p>
      </div>      
    </div>

    <div class='form-actions'>
      <%= submit_or_cancel(b) %>
    </div>
  </fieldset>
<% end %>

app/views/bets/_last_five.html.erb
<% 5.times do |i| %>
  <tr class="last_five">
    <td colspan="2"></td>
    <td><%= show_last_five_results(@result, i) %></td>
    <td><%= @result[0][i] %></td>
    <% if i < 1 %>
      <td><%= link_to('Ocultar', cancel_path(:format => :js), :remote => true, :class => 'cancel btn btn-inverse') %></td>
    <% end %>
  </tr>
<% end %>

app/views/bets/cancel.js.erb
$('.new_bet').remove();
$('.edit_bet').remove();
$('.last_five').remove();
$('#new_bet_link').show();
$('.edit_bet_link').show();
$('.destroy_bet_link').show();

app/views/bets/create.js.erb
$('.table').append("<%= escape_javascript(render(@bet)) %>");
$('#new_bet').remove();
$('#new_bet_link').show();

app/views/bets/destroy.js.erb
<%= render :file => 'bets/cancel.js.erb' %>
$('#<%= dom_id(@bet) %>').remove();

app/views/bets/edit.html.erb
<%= render 'form' %>

app/views/bets/edit.js.erb
<%= render :file => 'bets/cancel.js.erb' %>
$("<tr class='edit_bet'><td colspan='5'><%= escape_javascript render 'form' %></td></tr>").insertAfter('#<%= dom_id(@bet) %>');
$('#bet_numbers').val("<%= escape_javascript(@bet.numbers.join(',')) %>")
$("#<%= dom_id(@bet) + '_edit_link' %>").hide();
$('#new_bet_link').hide();

app/views/bets/fail_create.js.erb
alert("<%= @bet.errors.full_messages.to_sentence %>");

app/views/bets/index.html.erb
<div class="page-header">
  <h1>Suas Apostas</h1>
</div>

<div id="bets">
  <table class="table">
    <thead>
      <tr>
        <th>Tipo</th>
        <th>Números</th>
        <th>Resultado</th>
        <th>Concurso</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <%= render @bets %>
    </tbody>
  </table>
</div>

<%= link_to "Nova aposta", new_bet_path(:format => :js), :remote => true, :id => 'new_bet_link', :class => 'btn btn-primary' %>

app/views/bets/new.html.erb
<%= render 'form' %>

app/views/bets/new.js.erb
<%= render :file => 'bets/cancel.js.erb' %>
$("<%= escape_javascript render 'form' %>").insertAfter('#bets');
$('#new_bet_link').hide();

app/views/bets/show_last_five.js.erb
<%= render :file => 'bets/cancel.js.erb' %>
$("<%= escape_javascript render 'last_five' %>").insertAfter("#<%= dom_id(@bet) %>");

app/views/bets/update.js.erb
$('.edit_bet').remove();
$("#<%= dom_id(@bet) %>").replaceWith("<%= escape_javascript(render @bet) %>");
$('#new_bet_link').show();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sorte Sua</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta http-equiv="content-language" content="pt-br">
  <meta name="author" content="Luiz Augusto">
  <meta name="keywords" content="loteria, caixa, lotofacil, conferir, resultados, automaticamente, automatico, mega-sena, quina">
  <meta name="description" content="Confira seus resultados nas loterias brasileiras automaticamente.">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-10878888-3']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <%= link_to 'Sorte Sua', root_path, :class => 'brand' %>

        <div class="nav-collapse">
          <%= menu %>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span8 offset2">
        <%= content_tag(:p, notice, :class => 'notice alert alert-success') if notice.present? %>
        <%= content_tag(:p, alert, :class => 'alert') if alert.present? %>
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sorte Sua</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta http-equiv="content-language" content="pt-br">
  <meta name="author" content="Luiz Augusto">
  <meta name="keywords" content="loteria, caixa, lotofacil, conferir, resultados, automaticamente, automatico, mega-sena, quina">
  <meta name="description" content="Confira seus resultados nas loterias brasileiras automaticamente.">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-10878888-3']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <%= link_to 'Sorte Sua', root_path, :class => 'brand' %>

        <div class="nav-collapse">
          <ul class="nav">
            <li class="divider-vertical"></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to 'Cadastrar', new_user_registration_path %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to 'Contato', '#' %></li>
            <li class="divider-vertical"></li>        
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span8 offset2">
        <%= content_tag(:p, notice, :class => 'notice alert alert-success') if notice.present? %>
        <%= content_tag(:p, alert, :class => 'alert') if alert.present? %>
        <%= yield %>
      </div>
    </div>
    <div class="hero-unit">
      <h1>Sorte Sua</h1>
      <p>
        Confira automaticamente os seus resultados nas loterias brasileiras! Basta se cadastrar e inserir suas apostas para ver quantos pontos vocês fez no concurso atual e nos próximos. <br /> <br />
        <%= link_to 'Faça login', new_user_session_path, :class => 'btn btn-large'%> ou <%= link_to 'Cadastre-se', new_user_registration_path, :class => 'btn btn-primary btn-large' %>
      </p>
    </div>
    <div class="image-header">
      <span class="round-img">
        <img src="/assets/header.png" class="img"/>
      </span>
    </div>
  </div>

</body>
</html>